CREATE DATABASE IF NOT EXISTS Blog DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE Blog;

CREATE TABLE IF NOT EXISTS Writers
(
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	hashedPassword CHAR(60) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY (username)
)
ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS Posts
(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	publicationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	image VARCHAR(255) DEFAULT NULL,
	writerId TINYINT UNSIGNED,
	PRIMARY KEY (id),
	UNIQUE KEY (title),
	INDEX (publicationDate),
	INDEX (writerId),
	FOREIGN KEY (writerId) REFERENCES Writers(id) ON UPDATE CASCADE ON DELETE SET NULL
)
ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS Comments
(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) DEFAULT NULL,
	content VARCHAR(255) NOT NULL,
	publicationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	postId SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	INDEX (publicationDate),
	INDEX (postId),
	FOREIGN KEY (postId) REFERENCES Posts(id) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE = InnoDB DEFAULT CHARSET = utf8;