<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>Inscription ou authentification</title>
	</head>
	<body>
		<form action="inscription.php" method="post">
			<fieldset>
				<legend>Inscription</legend>
				<input type="text" name="pseudo" placeholder="utilisateur">
				<input type="password" name="passwordhash" placeholder="Mot de passe">
				<button type="submit">S'inscrire</button>
			</fieldset>
		</form>
		<form action="authentification.php" method="post">
			<fieldset>
				<legend>Authentification</legend>
				<input type="text" name="pseudo" placeholder="utilisateur">
				<input type="password" name="passwordhash" placeholder="Mot de passe">
				<button type="submit">S'authentifier</button>
			</fieldset>
		</form>
	</body>
</html>