<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css" media="all"/>
    <title>Accueil</title>
</head>
<body>
    <div class="topnav">
        <a class="active" href="#home">Formulaire</a>
        <a href="#modifier">Modifier</a>
        <a href="#supprimer">Supprimer</a>
    </div>
<form method="post" action="insertion.php" >
    <fieldset>
        <legend>Rédacteur</legend>
        <input type="text" name="titre" placeholder="Titre">
        <input type="text" id="idredacteur" placeholder="Pseudo">
    </fieldset>
  <textarea name="corps" rows="10" cols="30">Rédigez votre article.</textarea>
  <input type="submit">
</form>
</body>
</html>